"""Edit photo_id in products

Revision ID: 3220cd17c999
Revises: 82fd87de7a98
Create Date: 2025-08-11 01:14:18.627046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.utils.filetype


# revision identifiers, used by Alembic.
revision: str = '3220cd17c999'
down_revision: Union[str, None] = '82fd87de7a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo', app.db.utils.filetype.FileType(), nullable=True))
    op.drop_column('products', 'photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###
